### ISSUE TITLE
I cannot find v2.0.0 on pkg.go.dev

### ISSUE THREAD

**Issue by Bisstocuz** [NdoleStudio/lfu-cache#5]
ref: https://pkg.go.dev/github.com/NdoleStudio/lfu-cache

`go get` also works inproperly.

**Comment by AchoArnold** [comment]
Thanks @Bisstocuz 

This has been fixed by the latest commit. Use the `go get https://github.com/NdoleStudio/lfu-cache/v2` command instead.
